# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0
#
# This is a Kconfig fragment which can be used to enable debug-related options
# in the application. See the README for more details.

# Compiler
# CONFIG_DEBUG_OPTIMIZATIONS=y # Causing the app to crash
# CONFIG_NO_OPTIMIZATIONS=y      # -O0: all variables visible

# # west build -b reel_board --sysbuild samples/hello_world -- -DSB_CONFIG_BOOTLOADER_MCUBOOT=y
# mcuboot_CONFIG_DEBUG_OPTIMIZATIONS=y

# Logging
CONFIG_LOG=y
CONFIG_APP_LOG_LEVEL_DBG=y

# GDB thread awareness
# CONFIG_DEBUG_THREAD_INFO=y

# Exception info
CONFIG_EXCEPTION_DEBUG=y

# logging
CONFIG_LOG=y
CONFIG_APP_LOG_LEVEL_DBG=y
CONFIG_2CH_REMOTE_CONTROL_LOG_LEVEL_DBG=y
CONFIG_RC_CAR_LOG_LEVEL_DBG=y