# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0
#
# This file contains selected Kconfig options for the application.

CONFIG_INPUT=y
CONFIG_INPUT_GPIO_KEYS=y

CONFIG_SENSOR=y
CONFIG_2CH_REMOTE_CONTROL=y
CONFIG_RC_CAR=y
CONFIG_BOOTLOADER_MCUBOOT=y
# CONFIG_MCUBOOT_SIGNATURE_KEY_FILE="mcu_root_key.pem"